export const MOCK_STATS_ANALYST = {
  totalTransactions: 1284,
  openAlerts: 4,
  sarsFiled: 7,
  avgRiskScore: 32,
};

export const MOCK_STATS_ADMIN = {
  totalTransactions: 1284,
  totalSub: '+12 today',
  openAlerts: 4,
  openAlertsSub: '2 unassigned',
  sarsFiled: 7,
  sarsFiledSub: 'this month',
  overrideActions: 3,
  overrideActionsSub: 'by you',
};

export const MOCK_TRANSACTIONS = [
  { id: 'tx-0041', senderAccount: 'ACC-1192', receiverCountry: 'LU', amount: 14500, riskScore: 75, status: 'FLAGGED', firedRules: [{ name: 'LargeAmountRule', score: 40 }, { name: 'StructuringRule', score: 35 }] },
  { id: 'tx-0040', senderAccount: 'ACC-0033', receiverCountry: 'RU', amount: 9800, riskScore: 65, status: 'FLAGGED', firedRules: [{ name: 'HighRiskCountryRule', score: 35 }, { name: 'StructuringRule', score: 35 }] },
  { id: 'tx-0039', senderAccount: 'ACC-2210', receiverCountry: 'DE', amount: 1200, riskScore: 18, status: 'APPROVED', firedRules: [] },
  { id: 'tx-0038', senderAccount: 'ACC-7743', receiverCountry: 'IR', amount: 50000, riskScore: 100, status: 'FLAGGED', firedRules: [{ name: 'LargeAmountRule', score: 40 }, { name: 'HighRiskCountryRule', score: 35 }, { name: 'VelocityRule', score: 30 }] },
];

export const MOCK_ALERTS = [
  {
    id: 'ALT-0018', status: 'OPEN', riskScoreSnapshot: 75, analystNote: null,
    transaction: { id: 'tx-0041', senderAccount: 'ACC-1192', receiverCountry: 'LU', amount: 14500 },
    firedRules: [{ name: 'LargeAmountRule', score: 40 }, { name: 'StructuringRule', score: 35 }],
  },
  {
    id: 'ALT-0019', status: 'ESCALATED', riskScoreSnapshot: 100, analystNote: null,
    transaction: { id: 'tx-0038', senderAccount: 'ACC-7743', receiverCountry: 'IR', amount: 50000 },
    firedRules: [{ name: 'LargeAmountRule', score: 40 }, { name: 'HighRiskCountryRule', score: 35 }],
  },
  {
    id: 'ALT-0015', status: 'DISMISSED', riskScoreSnapshot: 45,
    analystNote: 'Known internal transfer, no suspicious activity.',
    transaction: { id: 'tx-0035', senderAccount: 'ACC-0091', receiverCountry: 'DE', amount: 9900 },
    firedRules: [{ name: 'StructuringRule', score: 35 }],
  },
];

export const MOCK_RULES = [
  { name: 'Large amount', threshold: '> \u20AC10,000', score: '+40 pts' },
  { name: 'High-risk country', threshold: 'IR, KP, RU, BY', score: '+35 pts' },
  { name: 'Structuring', threshold: '5 txs / 7 days', score: '+35 pts' },
  { name: 'Velocity', threshold: '20+ txs in 2h', score: '+30 pts' },
  { name: 'Dormant account', threshold: 'inactive 2yr+', score: '+25 pts' },
  { name: 'Round trip', threshold: 'round amounts', score: '+20 pts' },
];

export const MOCK_ADVANCED_STATS = [
  { label: 'SAR filing rate', value: '5.4%', sub: 'of all flagged alerts' },
  { label: 'Top risky account', value: 'ACC-7743', sub: 'score 100 \u00B7 3 alerts' },
  { label: 'Most triggered rule', value: 'LargeAmount', sub: 'fired 38 times' },
  { label: 'Overrides this month', value: '3', sub: '2 reopened \u00B7 1 reversed' },
];

export const MOCK_SAR_REPORTS = [
  {
    id: 'SAR-0007',
    alertId: 'ALT-0019',
    transactionId: 'tx-0038',
    amount: 50000,
    currency: 'EUR',
    filedAt: '2026-06-01T11:30:00Z',
    filedBy: 'analyst',
    pdfPath: '/reports/SAR-0007.pdf',
  },
  {
    id: 'SAR-0006',
    alertId: 'ALT-0012',
    transactionId: 'tx-0031',
    amount: 25000,
    currency: 'EUR',
    filedAt: '2026-05-28T09:15:00Z',
    filedBy: 'admin',
    pdfPath: '/reports/SAR-0006.pdf',
  },
  {
    id: 'SAR-0005',
    alertId: 'ALT-0009',
    transactionId: 'tx-0025',
    amount: 75000,
    currency: 'EUR',
    filedAt: '2026-05-22T14:00:00Z',
    filedBy: 'analyst',
    pdfPath: '/reports/SAR-0005.pdf',
  },
  {
    id: 'SAR-0004',
    alertId: 'ALT-0007',
    transactionId: 'tx-0019',
    amount: 9950,
    currency: 'EUR',
    filedAt: '2026-05-15T10:30:00Z',
    filedBy: 'analyst',
    pdfPath: '/reports/SAR-0004.pdf',
  },
  {
    id: 'SAR-0003',
    alertId: 'ALT-0005',
    transactionId: 'tx-0014',
    amount: 30000,
    currency: 'EUR',
    filedAt: '2026-05-10T16:45:00Z',
    filedBy: 'admin',
    pdfPath: '/reports/SAR-0003.pdf',
  },
  {
    id: 'SAR-0002',
    alertId: 'ALT-0003',
    transactionId: 'tx-0009',
    amount: 12500,
    currency: 'EUR',
    filedAt: '2026-05-05T08:20:00Z',
    filedBy: 'analyst',
    pdfPath: '/reports/SAR-0002.pdf',
  },
  {
    id: 'SAR-0001',
    alertId: 'ALT-0001',
    transactionId: 'tx-0003',
    amount: 50000,
    currency: 'EUR',
    filedAt: '2026-05-01T13:00:00Z',
    filedBy: 'analyst',
    pdfPath: '/reports/SAR-0001.pdf',
  },
];

export const MOCK_AUDIT_LOG = [
  {
    id: 'AUD-0012',
    entityType: 'SAR',
    entityId: 'SAR-0007',
    action: 'SAR_FILED',
    performedBy: 'analyst',
    note: 'SAR auto-generated on escalation of ALT-0019',
    timestamp: '2026-06-01T11:30:00Z',
  },
  {
    id: 'AUD-0011',
    entityType: 'ALERT',
    entityId: 'ALT-0019',
    action: 'ALERT_ESCALATED',
    performedBy: 'analyst',
    note: 'Confirmed suspicious pattern \u2014 large transfer to sanctioned country',
    timestamp: '2026-06-01T11:29:00Z',
  },
  {
    id: 'AUD-0010',
    entityType: 'ALERT',
    entityId: 'ALT-0019',
    action: 'ALERT_CREATED',
    performedBy: 'system',
    note: 'Alert auto-created. Score: 100. Rules: LargeAmountRule, HighRiskCountryRule, VelocityRule',
    timestamp: '2026-05-31T22:46:00Z',
  },
  {
    id: 'AUD-0009',
    entityType: 'ALERT',
    entityId: 'ALT-0018',
    action: 'ALERT_CREATED',
    performedBy: 'system',
    note: 'Alert auto-created. Score: 75. Rules: LargeAmountRule, StructuringRule',
    timestamp: '2026-06-01T10:31:00Z',
  },
  {
    id: 'AUD-0008',
    entityType: 'ALERT',
    entityId: 'ALT-0015',
    action: 'ALERT_DISMISSED',
    performedBy: 'analyst',
    note: 'Known internal transfer, no suspicious activity.',
    timestamp: '2026-05-30T15:30:00Z',
  },
  {
    id: 'AUD-0007',
    entityType: 'ALERT',
    entityId: 'ALT-0015',
    action: 'ALERT_CREATED',
    performedBy: 'system',
    note: 'Alert auto-created. Score: 45. Rules: StructuringRule',
    timestamp: '2026-05-30T14:00:00Z',
  },
  {
    id: 'AUD-0006',
    entityType: 'SAR',
    entityId: 'SAR-0006',
    action: 'SAR_FILED',
    performedBy: 'admin',
    note: 'SAR filed manually by administrator',
    timestamp: '2026-05-28T09:15:00Z',
  },
  {
    id: 'AUD-0005',
    entityType: 'ALERT',
    entityId: 'ALT-0012',
    action: 'ALERT_ESCALATED',
    performedBy: 'analyst',
    note: 'Velocity pattern confirmed suspicious',
    timestamp: '2026-05-28T09:14:00Z',
  },
  {
    id: 'AUD-0004',
    entityType: 'ALERT',
    entityId: 'ALT-0012',
    action: 'ALERT_CREATED',
    performedBy: 'system',
    note: 'Alert auto-created. Score: 70. Rules: VelocityRule, StructuringRule',
    timestamp: '2026-05-27T18:00:00Z',
  },
  {
    id: 'AUD-0003',
    entityType: 'SAR',
    entityId: 'SAR-0005',
    action: 'SAR_FILED',
    performedBy: 'analyst',
    note: 'SAR auto-generated on escalation of ALT-0009',
    timestamp: '2026-05-22T14:00:00Z',
  },
  {
    id: 'AUD-0002',
    entityType: 'ALERT',
    entityId: 'ALT-0009',
    action: 'ALERT_ESCALATED',
    performedBy: 'analyst',
    note: 'Large transfer to high-risk origin country confirmed',
    timestamp: '2026-05-22T13:59:00Z',
  },
  {
    id: 'AUD-0001',
    entityType: 'ALERT',
    entityId: 'ALT-0009',
    action: 'ALERT_CREATED',
    performedBy: 'system',
    note: 'Alert auto-created. Score: 90. Rules: LargeAmountRule, OriginCountryRule, HighRiskCountryRule',
    timestamp: '2026-05-22T10:00:00Z',
  },
];
